[Interface]
Address = 10.13.13.2
PrivateKey = CNwDn7ecQU37y5iG3D2RcZvfKXoEib+EvMP/RZDqOVQ=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = +8J+Ffuj7bowa93cW7SYab3waJZgCgkCoi7WeBIPxkg=
PresharedKey = y+aksrZPM1N3qqxaj88kvDJRAiB3jU7s8wr1gyWw2fY=
Endpoint = :51820
AllowedIPs = 0.0.0.0/0, ::/0
