services:

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - "8087:80"
    volumes:
      - ./nextcloud-data:/var/www/html
    restart: always


  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8088:80"
    volumes:
      - /:/srv
      - ./filebrowser-config/database.db:/database.db
      - ./filebrowser-config/settings.json:/config/settings.json
    restart: always


  duplicati:
    image: duplicati/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    ports:
      - "8200:8200"
    volumes:
      - ./duplicati-config:/config
      - /:/source:ro
    restart: always
