services:

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "5354:53/tcp"
      - "5354:53/udp"
      - "8092:80"
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - WEBPASSWORD=adminpassword123
    volumes:
      - ./pihole-etc:/etc/pihole
      - ./pihole-dnsmasq:/etc/dnsmasq.d
    restart: always


  hastebin:
    image: angristan/hastebin:latest
    container_name: hastebin
    ports:
      - "8093:7777"
    restart: always


  privatebin:
    image: privatebin/nginx-fpm-alpine:latest
    container_name: privatebin
    ports:
      - "8094:8080"
    restart: always


  snippetbox:
    image: pawelmalak/snippet-box:latest
    container_name: snippetbox
    ports:
      - "8095:8080"
    restart: always


